# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sas-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_959c4f9ea6a44e61b33450e4c82c69a4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5835125d09ca48dbb8ed6c64b336d7e4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_959c4f9ea6a44e61b33450e4c82c69a4 }}/sasapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sas-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a46bd36f9c2c4676aa91bd52c386ae3f }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_959c4f9ea6a44e61b33450e4c82c69a4 }}/sasapp:${{ github.sha }}'